from typing import Type, Any
from inspect import isawaitable
from ..base import *
import time


class Proxy(StatefulBase):
    def __init__(self,
                 server: Type[BaseServer] = BaseServer,
                 model: Type[BaseModel] = BaseModel,
                 codex: Type[BaseCodex] = BaseCodex,
                 db: Type[BaseDb] = BaseDb,
                 **kwargs):
        """The proxy object is the core of NBoost. It has four components:
        the model, server, db, and codex. The role of the proxy is to
        construct each component and create the route callback(search,
        train, status, not_found, and error).

        Each route callback is assigned a url path by the codex and then
        handed to the server to execute when it receives the respective url
        path request.The following __init__ contains the main executed
        functions in nboost.

        :param host: virtual host of the server.
        :param port: server port.
        :param ext_host: host of the external search api.
        :param ext_port: search api port.
        :param lr: learning rate of the model.
        :param model_ckpt: checkpoint for loading initial model
        :param max_seq_len: max combined token length
        :param batch_size: batch size for running through rerank model
        :param data_dir: data directory to cache the model.
        :param multiplier: the factor to multiply the search request by. For
            example, in the case of Elasticsearch if the client requests 10
            results and the multiplier is 6, then the model should receive 60
            results to rank and refine down to 10 (better) results.
        :param field: a tag for the field in the search api result that the
            model should rank results by.
        :param server: uninitialized server class
        :param model: uninitialized model class
        :param codex: uninitialized codex class
        :param db: uninitialized db class
        """
        super().__init__(**kwargs)
        self.kwargs = kwargs

        # pass command line arguments to instantiate each component
        server = server(**kwargs)
        model = model(**kwargs)
        codex = codex(**kwargs)
        db = db(**kwargs)

        def track(f: Any):
            """Tags and times each component for benchmarking purposes. The
            data generated by track() is sent to the db who decides what to do
            with it (e.g. log, add to /status, etc...)"""

            is_proxy = False if hasattr(f, '__self__') else True
            cls = self.__class__.__name__ if is_proxy else f.__self__.__class__.__name__
            ident = (cls, f.__name__)

            async def decorator(*args):
                try:
                    start = time.perf_counter()
                    res = f(*args)
                    ret = await res if isawaitable(res) else res
                    ms = (time.perf_counter() - start) * 1000
                    db.lap(ms, *ident)
                except Exception as e:
                    # reraise if not proxy to escape route
                    if not is_proxy:
                        raise e

                    self.logger.error(repr(e), exc_info=True)
                    ret = codex.catch(e)
                return ret
            return decorator

        @track
        async def search(request: Request) -> Response:
            """The role of the search route is to take a request from the
            client, balloon it by the multipler and ask for that larger request
            from the search api, then filter the larger results with the
            model to return better results. """

            # Codex figures out how many results the client wants.
            topk = await track(codex.topk)(request)

            # Codex alters the request to make a larger one.
            await track(codex.magnify)(request, topk)

            # The server asks the search api for the larger request.
            response = await track(server.ask)(request)

            # The codex parses out the query from the amplified req and res.
            query, choices = await track(codex.parse)(request, response)

            # the model adds a rank to each of the choices
            await track(model.rank)(query, choices)

            # the db saves the query and choices, and assigns query ids
            # and choice ids if they we're not previously assigned (for train)
            await track(db.save)(query, choices)

            # the codex formats the new (nboosted) response with the context
            # from the entire search pipeline.
            await track(codex.pack)(topk, response, query, choices)
            return response

        @track
        async def train(request: Request) -> Response:
            """The role of the train route is to receive a query id and choice
            id from the client and train the model to choose that one next
            time for lack of better words."""

            # Parse out the query id and choice id(s) from the client request.
            qid, cids = await track(codex.pluck)(request)

            # Db retrieves the content it saved during search(). It also
            # assigns a label to each choice based on the clients request.
            query, choices = await track(db.get)(qid, cids)
            await track(model.train)(query, choices)

            # acknowledge that the request was sent to the model
            response = await track(codex.ack)(qid, cids)
            return response

        @track
        async def status(_1: Request) -> Response:
            """Status() chains the state from each component in order to
            return a formatted dictionary for /status"""
            state = server.chain_state({})
            state = codex.chain_state(state)
            state = model.chain_state(state)
            state = db.chain_state(state)
            state = codex.pulse(state)
            return state

        @track
        async def not_found(_1: Any) -> Any:
            """What to do when none of the paths given to the server match
            the path requested by the client."""
            _2 = await track(server.forward)(_1)
            return _2

        # create functional routes for the server
        server.create_app([
            codex.SEARCH + (search,),
            codex.TRAIN + (train,),
            codex.STATUS + (status,),
        ], not_found_handler=not_found)

        self.server = server

    def start(self):
        self.server.start()
        self.server.is_ready.wait()

    def close(self):
        self.server.stop()
        self.server.join()
